blueprint:
  name: Simple Climate
  description: Automatisation pour contrôler les préréglages du thermostat basé sur un calendrier personnalisé
  domain: automation
  input:
    thermostat_entity:
      name: Entité du thermostat
      description: Sélectionne le thermostat à contrôler
      selector:
        entity:
          domain: climate
    schedule_entity:
      name: Entité du calendrier
      description: Sélectionne l'entité "schedule" à utiliser pour planifier le chauffage
      selector:
        entity:
          domain: schedule
    preset_when_on:
      name: Préréglage lorsque le calendrier est activé
      description: Sélectionne le préréglage lorsque le calendrier est en position "on"
      selector:
        select:
          options:
            - 'comfort'
            - 'eco'
            - 'sleep'
            - 'away'
            - 'home'
    preset_when_off:
      name: Préréglage lorsque le calendrier est désactivé
      description: Sélectionne le préréglage lorsque le calendrier est en position "off"
      selector:
        select:
          options:
            - 'comfort'
            - 'eco'
            - 'sleep'
            - 'away'
            - 'home'

mode: restart
max_exceeded: silent

trigger:
  - platform: state
    entity_id: !input schedule_entity

condition: []

action:
  - choose:
      - conditions:
          - condition: state
            entity_id: !input schedule_entity
            state: "on"
        sequence:
          - service: climate.set_preset_mode
            target:
              entity_id: !input thermostat_entity
            data:
              preset_mode: !input preset_when_on
      - conditions:
          - condition: state
            entity_id: !input schedule_entity
            state: "off"
        sequence:
          - service: climate.set_preset_mode
            target:
              entity_id: !input thermostat_entity
            data:
              preset_mode: !input preset_when_off